### ISSUE TITLE
Please tag v0.0.4

### ISSUE THREAD

**Issue by ronkorving** [ericclemmons/unique-selector#10]
I can't install this component without its tag, and I don't like using `"*"` versions.

Thanks :)

**Comment by ericclemmons** [comment]
Whoops!  Apparently it was tagged, but I never `git push --tags`!
> https://github.com/ericclemmons/unique-selector/releases

Let me know if this works (or doesn't) for you now :)

**Comment by ronkorving** [comment]
Thanks :)
