### ISSUE TITLE
Looking for Contributors / Owners

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/unique-selector#12]
First, I apologize that I can't spend any time on this project. Plus, I have a family and a full-time job, so I'm not _really_ apologizing ;)

This project should be updated to work better with NPM & modern stacks.

Therefore, **respond to this thread with the following info for Github & NPM publishing rights**:

1. Github username (well, it'll be on the issue, but just to show you're serious :D)
2. NPM email / user so I can give you `npm publisher` access.

If no one steps up, I'll mark this project as deprecated and let the community find alternatives.

**Comment by AvraamMavridis** [comment]
Hey @ericclemmons , I will like to take over this project, I have done some work on that in a private project using `es6`. 

Github: https://github.com/AvraamMavridis
Npm: https://www.npmjs.com/~avrmav
Twitter: https://twitter.com/avraamakis

**Comment by ericclemmons** [comment]
@AvraamMavridis Awesome!  I really appreciate it!

```shell
  npm owner ls
avrmav <avr.mav@gmail.com>
ericclemmons <eric@smarterspam.com>
```

**Comment by AvraamMavridis** [comment]
:smile:

**Comment by AvraamMavridis** [comment]
@ericclemmons Can you also add me as collaborator in the repo, to be able to merge PRs etc ?

**Comment by ericclemmons** [comment]
@AvraamMavridis Done!  Sorry I missed it.

Anything else you'd like? :)

**Comment by AvraamMavridis** [comment]
@ericclemmons perfect! thx! :)
