### ISSUE TITLE
Uncaught DOMException when element id start with a number. 

### ISSUE THREAD

**Issue by pbibalan** [ericclemmons/unique-selector#28]
When element id start with a number the following error is raised:

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element' on 'Element': '#123' is not a valid selector. at testUniqueness
```
Inside:
```
function testUniqueness(element, selector) {
  var parentNode = element.parentNode;

  var elements = parentNode.querySelectorAll(selector);
  return elements.length === 1 && elements[0] === element;
}
```
As far as I can tell, this is because ```querySelectorAll``` doesn't accept ids that start with a number event though they are valid HTML5 ids.

https://stackoverflow.com/questions/37270787/uncaught-syntaxerror-failed-to-execute-queryselector-on-document

> You are allowed to use IDs that start with a digit in your HTML5 documents:
> 
> The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. The value must not contain any space characters.
> 
> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.
> But querySelector method uses CSS3 selectors for querying the DOM and CSS3 doesn't support ID selectors that start with a digit:
> 
> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit.
> Use a value like b22 for the ID attribute and your code will work.

**Comment by AvraamMavridis** [comment]
@pbibalan  Thx for the info and sorry for the late reply, I will investigate that in a few days :)

**Comment by osnysantos** [comment]
I'm getting a similar output:

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.ng-disabled=true' is not a valid selector.
```

When passing an element from an Angular website. Here is the element:

```
<li ng-class="getMenuItemPropClasses(item)" ng-repeat="item in menuItems" ng-init="pIndex = $index" ng-include="'sidebar-renderer.html'" ng-click="toggleCollapse(pIndex, true)" class="ng-scope  activeng-disabled=true"></li>
```

**Comment by AvraamMavridis** [comment]
@osnysantos thx, I will try to find some time to look at it. Probably during the weekend.

**Comment by G0dwin** [comment]
+1, any updates on this issue?

**Comment by QGB** [comment]
'#1' is not a valid selector.

**Comment by nickforddesign** [comment]
Yeah just encountered this as well, any updates?
